version: "3"
# this file uses prebuilt image in dockerhub
services:
  jekyll:
    platform: linux/amd64
    image: amirpourmand/al-folio
    ports:
      - 8080:8080
    volumes:
      - .:/srv/jekyll
